version: '2.3'

services:
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wishlist"
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres-volume:/var/lib/postgresql/data

  user-api:
    build: ./user-api
    command: npm run dev
    healthcheck:
      test: curl --silent --fail localhost:3000/_health_check || exit 1
      interval: 5s
      retries: 5
    volumes:
      - ./user-api/src/:/app/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  wishlist-api:
    build: ./wishlist-api
    healthcheck:
      test: curl --silent --fail localhost:4000/_health_check || exit 1
      interval: 5s
      retries: 5
    volumes:
      - ./wishlist-api/src/:/app/src
    ports:
      - 4000:4000
    depends_on:
      - postgres
    command: sh -c "/wait && /init"
    environment:
    - NODE_ENV=development
    - WAIT_HOSTS=postgres:5432
    - WAIT_HOSTS_TIMEOUT=300
    - WAIT_SLEEP_INTERVAL=5
    - WAIT_HOST_CONNECT_TIMEOUT=5
